[project]
name = "rlax"
version = "0.1.0"
description = "Reinforcement Learning in JAX."
readme = "README.md"
requires-python = ">=3.12"
license = "Apache-2.0"
authors = [
  { name = "huterguier", email = "huterguier@gmail.com" }
]
dependencies = [
  "jax[cuda]",
  "flax",
  "optax",
  "distrax",
  "hydra-core",
  "tqdx",
  "lox@git+https://github.com/huterguier/lox",
  "gxm@git+https://github.com/huterguier/gxm",
]

[project.optional-dependencies]
dev = [
  "ruff",
]
examples = [
  "gxm[gymnax]@git+https://github.com/huterguier/gxm",
]

[tool.ruff]
target-version = "py312"
line-length = 88

[tool.ruff.lint]
select = ["E", "F", "I", "W", "UP", "B"]
ignore = ["E501"]
